<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="Paramore.Brighter" Version="10.0.3" />
    <PackageReference Include="Paramore.Brighter.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Paramore.Darker" Version="4.1.1" />
    <ProjectReference Include="..\PaymentGateway.Domain\PaymentGateway.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CycloneDdsDisableCodeGen>false</CycloneDdsDisableCodeGen>
  </PropertyGroup>

</Project>
